name: Go
on: [push]
jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    env:
        GOBIN2: ${HOME}/go/bin
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test
